apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: kube-scheduler-leases
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-scheduler-leases
subjects:
  - kind: ServiceAccount
    name: sample-scheduler-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-scheduler-leases
  apiGroup: rbac.authorization.k8s.io