apiVersion: kubescheduler.config.k8s.io/v1beta3
clientConnection:
  acceptContentTypes: application/json
  burst: 100
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: /etc/kubernetes/scheduler.conf
  qps: 50
enableContentionProfiling: false
enableProfiling: false
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  resourceLock: leases
  resourceName: kube-scheduler
  resourceNamespace: kube-system
  retryPeriod: 2s
parallelism: 16
percentageOfNodesToScore: 0
podInitialBackoffSeconds: 1
podMaxBackoffSeconds: 10
profiles:
  - schedulerName: sample-scheduler
    pluginConfig:
      - args:
          favoriteColor: #326CE5
          favorNumber: 7
          thanksTo: "Kubernetes"
        name: sample-plugin
    plugins:
      preFilter:
        enabled:
          - name: sample-plugin
      filter:
        enabled:
          - name: sample-plugin
